<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\GameMatch;
use App\Models\MatchStatus;
use Illuminate\Database\Seeder;

class GameMatchSeeder extends Seeder
{
    // Mapea los IDs del mock a los IDs de la DB (orden de UserSeeder)
    // id=1: admin (nmpiovano)  id=2: mock-current  id=3: u1 ... id=18: u16
    private const USER_MAP = [
        'mock-current' => 2,
        'u1'  => 3,  'u2'  => 4,  'u3'  => 5,
        'u4'  => 6,  'u5'  => 7,  'u6'  => 8,
        'u7'  => 9,  'u8'  => 10, 'u9'  => 11,
        'u10' => 12, 'u11' => 13, 'u12' => 14,
        'u13' => 15, 'u14' => 16, 'u15' => 17, 'u16' => 18,
    ];

    public function run(): void
    {
        $statuses = MatchStatus::query()->pluck('id', 'name');

        $matches = [
            [
                'pitch_type'              => 'f5',
                'players_count'           => 10,
                'open_slots'              => 10,
                'date'                    => '2030-06-15',
                'time'                    => '19:00',
                'venue_name'              => 'Cancha Siempre Futura',
                'neighborhood'            => 'Microcentro',
                'address'                 => 'Av. Corrientes 800, CABA',
                'lat'                     => -34.6,
                'lng'                     => -58.38,
                'description'             => 'Partido con fecha lejana para probar botón Anotarme.',
                'price'                   => 10000,
                'football_level'          => 4,
                'gender'                  => 'mixto',
                'field_surface'           => 'sintetico',
                'establishment_covered'   => 'techado',
                'establishment_amenities' => ['vestuario'],
                'created_by'              => 'mock-current',
                'status'                  => 'open',
            ],
            [
                'pitch_type'              => 'f5',
                'players_count'           => 10,
                'open_slots'              => 2,
                'date'                    => '2025-03-15',
                'time'                    => '18:00',
                'venue_name'              => 'Cancha Los Andes',
                'neighborhood'            => 'Almagro',
                'address'                 => 'Av. Díaz Vélez 2200, CABA',
                'lat'                     => -34.6037,
                'lng'                     => -58.3816,
                'description'             => 'Partido tranqui nivel 4, buena onda.',
                'price'                   => 12000,
                'football_level'          => 4,
                'gender'                  => 'mixto',
                'field_surface'           => 'cemento',
                'establishment_covered'   => 'descubierto',
                'establishment_amenities' => [],
                'created_by'              => 'mock-current',
                'status'                  => 'open',
            ],
            [
                'pitch_type'              => 'f7',
                'players_count'           => 14,
                'open_slots'              => 6,
                'date'                    => '2025-03-16',
                'time'                    => '19:30',
                'venue_name'              => 'Complejo Deportivo Norte',
                'neighborhood'            => 'Colegiales',
                'address'                 => 'Av. Beiró 3100, CABA',
                'lat'                     => -34.6157,
                'lng'                     => -58.4333,
                'description'             => 'Partido competitivo nivel 8. Traer camiseta.',
                'price'                   => 18000,
                'football_level'          => 8,
                'gender'                  => 'masculino',
                'field_surface'           => 'sintetico',
                'establishment_covered'   => 'techado',
                'establishment_amenities' => ['buffet', 'vestuario'],
                'created_by'              => 'u2',
                'status'                  => 'cancelled',
            ],
            [
                'pitch_type'              => 'f11',
                'players_count'           => 22,
                'open_slots'              => null,
                'date'                    => '2025-03-20',
                'time'                    => '10:00',
                'venue_name'              => 'Estadio Municipal',
                'neighborhood'            => 'Palermo',
                'address'                 => 'Av. Del Libertador 2100, CABA',
                'lat'                     => -34.5895,
                'lng'                     => -58.3974,
                'description'             => 'Fútbol 11 amistoso, todos bienvenidos.',
                'price'                   => 25000,
                'football_level'          => 5,
                'gender'                  => 'mixto',
                'field_surface'           => 'sintetico',
                'establishment_covered'   => 'descubierto',
                'establishment_amenities' => ['vestuario'],
                'created_by'              => 'u3',
                'status'                  => 'open',
            ],
            [
                'pitch_type'              => 'f5',
                'players_count'           => 10,
                'open_slots'              => null,
                'date'                    => '2025-03-14',
                'time'                    => '20:00',
                'venue_name'              => 'Cancha Central',
                'neighborhood'            => 'Caballito',
                'address'                 => 'Av. Rivadavia 5200, CABA',
                'lat'                     => -34.61,
                'lng'                     => -58.39,
                'description'             => 'Partido nuevo, nivel 3.',
                'price'                   => 8000,
                'football_level'          => 3,
                'gender'                  => 'femenino',
                'field_surface'           => 'caucho',
                'establishment_covered'   => 'techado',
                'establishment_amenities' => ['vestuario'],
                'created_by'              => 'u4',
                'status'                  => 'open',
            ],
            [
                'pitch_type'              => 'f5',
                'players_count'           => 10,
                'open_slots'              => null,
                'date'                    => '2025-03-01',
                'time'                    => '10:00',
                'venue_name'              => 'Cancha Pasada',
                'neighborhood'            => 'Caballito',
                'address'                 => 'Av. Rivadavia 5200, CABA',
                'lat'                     => -34.605,
                'lng'                     => -58.385,
                'description'             => 'Partido ya jugado. Solo el creador puede valorar.',
                'price'                   => 10000,
                'football_level'          => 5,
                'gender'                  => 'mixto',
                'field_surface'           => 'cemento',
                'establishment_covered'   => 'descubierto',
                'establishment_amenities' => [],
                'created_by'              => 'mock-current',
                'status'                  => 'finished',
            ],
            [
                'pitch_type'              => 'f8',
                'players_count'           => 16,
                'open_slots'              => null,
                'date'                    => '2025-03-18',
                'time'                    => '18:30',
                'venue_name'              => 'Polideportivo Sur',
                'neighborhood'            => 'Belgrano',
                'address'                 => 'Av. Rivadavia 5200, CABA',
                'lat'                     => -34.6,
                'lng'                     => -58.41,
                'description'             => 'Casi lleno, anotate ya.',
                'price'                   => 15000,
                'football_level'          => 6,
                'gender'                  => 'mixto',
                'field_surface'           => 'sintetico',
                'establishment_covered'   => 'techado',
                'establishment_amenities' => ['buffet', 'vestuario'],
                'created_by'              => 'u5',
                'status'                  => 'open',
            ],
            [
                'pitch_type'              => 'f5',
                'players_count'           => 10,
                'open_slots'              => null,
                'date'                    => '2025-02-15',
                'time'                    => '18:00',
                'venue_name'              => 'Cancha Parque Chacabuco',
                'neighborhood'            => 'Chacabuco',
                'address'                 => 'Av. Chacabuco 1200, CABA',
                'lat'                     => -34.608,
                'lng'                     => -58.39,
                'description'             => 'Partido pasado - amistoso nivel 5.',
                'price'                   => 9000,
                'football_level'          => 5,
                'gender'                  => 'masculino',
                'field_surface'           => 'caucho',
                'establishment_covered'   => 'descubierto',
                'establishment_amenities' => ['buffet'],
                'created_by'              => 'u1',
                'status'                  => 'finished',
            ],
            [
                'pitch_type'              => 'f7',
                'players_count'           => 14,
                'open_slots'              => null,
                'date'                    => '2025-02-22',
                'time'                    => '19:00',
                'venue_name'              => 'Complejo Roca',
                'neighborhood'            => 'Colegiales',
                'address'                 => 'Av. Roca 1200, CABA',
                'lat'                     => -34.612,
                'lng'                     => -58.42,
                'description'             => 'Partido pasado - competitivo nivel 7.',
                'price'                   => 14000,
                'football_level'          => 7,
                'gender'                  => 'masculino',
                'field_surface'           => 'sintetico',
                'establishment_covered'   => 'techado',
                'establishment_amenities' => ['vestuario'],
                'created_by'              => 'u2',
                'status'                  => 'finished',
            ],
            [
                'pitch_type'              => 'f5',
                'players_count'           => 10,
                'open_slots'              => null,
                'date'                    => '2025-02-28',
                'time'                    => '10:30',
                'venue_name'              => 'Cancha Palermo',
                'neighborhood'            => 'Palermo',
                'address'                 => 'Av. Alvear 1200, CABA',
                'lat'                     => -34.595,
                'lng'                     => -58.375,
                'description'             => 'Partido pasado - nivel 6.',
                'price'                   => 11000,
                'football_level'          => 6,
                'gender'                  => 'femenino',
                'field_surface'           => 'cemento',
                'establishment_covered'   => 'descubierto',
                'establishment_amenities' => [],
                'created_by'              => 'u3',
                'status'                  => 'finished',
            ],
            [
                'pitch_type'              => 'f5',
                'players_count'           => 10,
                'open_slots'              => null,
                'date'                    => '2025-04-05',
                'time'                    => '20:00',
                'venue_name'              => 'Cancha Belgrano',
                'neighborhood'            => 'Belgrano',
                'address'                 => 'Av. Belgrano 1200, CABA',
                'lat'                     => -34.602,
                'lng'                     => -58.388,
                'description'             => 'Partido futuro - nivel 8, traer camiseta.',
                'price'                   => 13000,
                'football_level'          => 8,
                'gender'                  => 'masculino',
                'field_surface'           => 'sintetico',
                'establishment_covered'   => 'techado',
                'establishment_amenities' => ['buffet', 'vestuario'],
                'created_by'              => 'u7',
                'status'                  => 'open',
            ],
        ];

        foreach ($matches as $data) {
            $statusId = $statuses[$data['status']];
            $createdBy = self::USER_MAP[$data['created_by']];

            GameMatch::query()->create([
                'pitch_type'              => $data['pitch_type'],
                'players_count'           => $data['players_count'],
                'open_slots'              => $data['open_slots'],
                'date'                    => $data['date'],
                'time'                    => $data['time'],
                'venue_name'              => $data['venue_name'],
                'neighborhood'            => $data['neighborhood'],
                'address'                 => $data['address'],
                'lat'                     => $data['lat'],
                'lng'                     => $data['lng'],
                'description'             => $data['description'],
                'price'                   => $data['price'],
                'football_level'          => $data['football_level'],
                'gender'                  => $data['gender'],
                'field_surface'           => $data['field_surface'],
                'establishment_covered'   => $data['establishment_covered'],
                'establishment_amenities' => $data['establishment_amenities'],
                'status_id'               => $statusId,
                'created_by'              => $createdBy,
            ]);
        }
    }
}
